# Generated by Django 4.2.4 on 2023-09-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='created_at',
        ),
        migrations.AddField(
            model_name='customuser',
            name='favorite_film',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
